### ISSUE TITLE
documentation update

### ISSUE THREAD

**Issue by jabadge** [icepack/website#4]
On the Developer -> Maintenance page of the documentation, it would be helpful to tell people how to update their python environment when new dependencies are added to icepack. Something like: "To check for and install any missing dependencies, navigate to the icepack directory and run 'pip3 install -e .'"

**Comment by jabadge** [comment]
Oh cool, I didn't know you could transfer issues. I addressed this issue in my recent pull request, so I'm going to close this.

**Comment by danshapero** [comment]
Neither did I?!
